#!/bin/bash
#complete -f -X '!*.@(avi|mkv|mp4|mov|ogm|mpg|divx)' -o plusdirs play

file_name=$1
file_root=$(echo $file_name | sed 's/\.[a-zA-Z0-9]*$//')
index=0
while read subtitle; do
  ((index++))
  echo -e "[$index]\t$subtitle"
  subtitles[$index]="$subtitle"
done < <(ls "${file_root}"*.srt 2> /dev/null)

if [[ $index -eq 1 ]]; then
  subtitle=${subtitles[1]}
elif [[ $index -gt 1 ]]; then
  read -p 'Whitch subtitle should we use? ' index
  subtitle=${subtitles[$index]}
fi

if [[ -z $subtitle ]]; then
  echo "Playing without subtitles"
  omxplayer -b -o hdmi -r "$file_name"
else
  echo "Playing with the following subtitles: $subtitle"
  omxplayer -b -o hdmi -r --subtitles "$subtitle" "$file_name"
fi

