#!/bin/bash

file_name=$1
file_root=$(echo $file_name | sed 's/\.[a-zA-Z0-9]*$//')

index=1
while read subtitle; do
  echo -e "[$index]\t$subtitle"
  subtitles[$index]="$subtitle"
  ((index++))
done < <(ls "${file_root}"*.srt 2> /dev/null)

if [[ $index -gt 1 ]]; then
  read -p 'Whitch subtitle should we use? ' index
  subtitle=${subtitles[$index]}
fi

if [[ -z $subtitle ]]; then
  echo "Playing without subtitles"
  omxplayer -b -o local "$file_name"
else
  echo "Playing with the following subtitles: $subtitle"
  omxplayer -b -o local --subtitles "$subtitle" "$file_name"
fi

